apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
  namespace: demo
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web-container
        image: 746669196057.dkr.ecr.us-east-2.amazonaws.com/web-app:5
        ports:
        - containerPort: 5000
